"""initial

Revision ID: 2d2bfbbdcc04
Revises:
Create Date: 2026-04-28 16:31:06.460095

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d2bfbbdcc04"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "user", name="userrole", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "COMPLETED",
                "ARCHIVED",
                name="projectstatus",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "file_storage_type",
            sa.Enum(
                "LOCAL", "S3", name="filestoragetype", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("file_uuid", sa.String(length=36), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "APPLICATION_PDF",
                "APPLICATION_MSWORD",
                "APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT",
                "APPLICATION_VND_MS_EXCEL",
                "APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET",
                "IMAGE_JPEG",
                "IMAGE_PNG",
                "IMAGE_SVG",
                "TEXT_PLAIN",
                "TEXT_CSV",
                "MIXED",
                "APPLICATION_XML",
                "APPLICATION_JSON",
                "TEXT_RTF",
                name="filetype",
                native_enum=False,
                length=100,
            ),
            nullable=False,
        ),
        sa.Column(
            "file_creator",
            sa.Enum("user", "system", name="filecreator", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("file_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "preprocessing_strategy",
            sa.Enum(
                "FULL_DOCUMENT",
                "ROW_BY_ROW",
                "CUSTOM",
                name="preprocessingstrategy",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_uuid"),
    )
    op.create_index(
        "ix_file_hash_project", "files", ["file_hash", "project_id"], unique=False
    )
    op.create_table(
        "ground_truth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("file_uuid", sa.String(length=36), nullable=False),
        sa.Column("data_cache", sa.JSON(), nullable=True),
        sa.Column("id_column_name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_uuid"),
    )
    op.create_table(
        "preprocessing_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("pdf_backend", sa.String(length=50), nullable=True),
        sa.Column("ocr_backend", sa.String(length=50), nullable=True),
        sa.Column("use_ocr", sa.Boolean(), nullable=False),
        sa.Column("force_ocr", sa.Boolean(), nullable=False),
        sa.Column("ocr_languages", sa.JSON(), nullable=True),
        sa.Column("ocr_model", sa.String(length=100), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("additional_settings", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("system_prompt", sa.String(), nullable=True),
        sa.Column("user_prompt", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schemas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("schema_name", sa.String(length=100), nullable=False),
        sa.Column("schema_definition", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("preprocessing_config_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preprocessing_config_id"],
            ["preprocessing_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ground_truth_id", sa.Integer(), nullable=False),
        sa.Column("schema_id", sa.Integer(), nullable=False),
        sa.Column("schema_field", sa.String(length=200), nullable=False),
        sa.Column("ground_truth_field", sa.String(length=200), nullable=False),
        sa.Column(
            "field_type",
            sa.Enum(
                "STRING",
                "NUMBER",
                "BOOLEAN",
                "CATEGORY",
                "DATE",
                "ARRAY",
                "OBJECT",
                name="fieldtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "comparison_method",
            sa.Enum(
                "EXACT",
                "FUZZY",
                "NUMERIC",
                "BOOLEAN",
                "CATEGORY",
                "DATE",
                name="comparisonmethod",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("comparison_options", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"],
            ["ground_truth.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ground_truth_id",
            "schema_id",
            "schema_field",
            name="uq_field_mapping_gt_schema_field",
        ),
    )
    op.create_table(
        "preprocessing_configuration_file_association",
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["preprocessing_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("configuration_id", "file_id"),
    )
    op.create_table(
        "preprocessing_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("configuration_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="preprocessingstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("processed_files", sa.Integer(), nullable=False),
        sa.Column("failed_files", sa.Integer(), nullable=False),
        sa.Column("skipped_files", sa.Integer(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("rollback_on_cancel", sa.Boolean(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_completion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("task_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["preprocessing_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_preprocessing_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("preprocessing_task_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="preprocessingstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("processing_time", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preprocessing_task_id"],
            ["preprocessing_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preprocessing_task_file_association",
        sa.Column("preprocessing_task_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preprocessing_task_id"],
            ["preprocessing_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("preprocessing_task_id", "file_id"),
    )
    op.create_table(
        "trials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("schema_id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("document_set_id", sa.Integer(), nullable=True),
        sa.Column("document_ids", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="trialstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("llm_model", sa.String(length=100), nullable=False),
        sa.Column("api_key", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=100), nullable=False),
        sa.Column("bypass_celery", sa.Boolean(), nullable=False),
        sa.Column("advanced_options", sa.JSON(), nullable=False),
        sa.Column("docs_done", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("rollback_on_cancel", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_set_id"],
            ["document_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("original_file_id", sa.Integer(), nullable=False),
        sa.Column("file_preprocessing_task_id", sa.Integer(), nullable=True),
        sa.Column("preprocessing_config_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("document_name", sa.String(length=500), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("preprocessed_file_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_preprocessing_task_id"],
            ["file_preprocessing_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preprocessed_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preprocessing_config_id"],
            ["preprocessing_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "original_file_id",
            "preprocessing_config_id",
            "document_name",
            name="_document_uniqueness",
        ),
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.Integer(), nullable=False),
        sa.Column("groundtruth_id", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("field_metrics", sa.JSON(), nullable=False),
        sa.Column("document_metrics", sa.JSON(), nullable=False),
        sa.Column("confusion_matrices", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["groundtruth_id"],
            ["ground_truth.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trial_id"],
            ["trials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_set_association",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("document_set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_set_id"],
            ["document_sets.id"],
        ),
        sa.PrimaryKeyConstraint("document_id", "document_set_id"),
    )
    op.create_table(
        "evaluation_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=200), nullable=False),
        sa.Column("ground_truth_value", sa.String(), nullable=True),
        sa.Column("predicted_value", sa.String(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preprocessing_task_document_association",
        sa.Column("preprocessing_task_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preprocessing_task_id"],
            ["preprocessing_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("preprocessing_task_id", "document_id"),
    )
    op.create_table(
        "trial_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("additional_content", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trial_id"],
            ["trials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trial_id", "document_id", name="uq_trial_document"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trial_results")
    op.drop_table("preprocessing_task_document_association")
    op.drop_table("evaluation_metrics")
    op.drop_table("document_set_association")
    op.drop_table("evaluations")
    op.drop_table("documents")
    op.drop_table("trials")
    op.drop_table("preprocessing_task_file_association")
    op.drop_table("file_preprocessing_tasks")
    op.drop_table("preprocessing_tasks")
    op.drop_table("preprocessing_configuration_file_association")
    op.drop_table("field_mappings")
    op.drop_table("document_sets")
    op.drop_table("schemas")
    op.drop_table("prompts")
    op.drop_table("preprocessing_configurations")
    op.drop_table("ground_truth")
    op.drop_index("ix_file_hash_project", table_name="files")
    op.drop_table("files")
    op.drop_table("projects")
    op.drop_table("users")
    op.drop_table("invitations")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
