#!/usr/bin/env bash
#
# Generate THIRD_PARTY_NOTICES.md — license attribution for the third-party
# open-source components bundled in the SHIPPED LLMAIx Web artifacts:
#   * backend  → Python production dependencies  (uv, --no-dev)
#   * frontend → npm production dependencies      (license-checker, --production)
#
# Dev/build-only dependencies (torch, docling, eslint, vite, …) are intentionally
# excluded — they are not distributed in the production Docker images.
#
# Requirements: uv, node/npx. Everything else runs in throwaway environments so
# your local .venv / node_modules are not modified.
#
# Usage: ./scripts/generate-third-party-notices.sh
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD_PARTY_NOTICES.md"
TMP_REQS="$(mktemp)"
trap 'rm -f "$TMP_REQS"' EXIT

VERSION="$(grep -m1 '^version = ' pyproject.toml | cut -d'"' -f2)"

# License overrides for packages whose license pip-licenses cannot read from
# metadata (they publish it only in their repo). Format: "pkg=SPDX;pkg=SPDX".
#   * mistralai — Apache-2.0 (https://github.com/mistralai/client-python, LICENSE)
LICENSE_OVERRIDES="mistralai=Apache-2.0"

# Apply LICENSE_OVERRIDES to a pip-licenses markdown table on stdin, preserving
# the License column width so the table stays aligned.
apply_license_overrides() {
  awk -v overrides="$LICENSE_OVERRIDES" '
    BEGIN {
      n = split(overrides, pairs, ";")
      for (i = 1; i <= n; i++) { split(pairs[i], kv, "="); map[kv[1]] = kv[2] }
    }
    /^\|/ {
      name = $2; gsub(/^ +| +$/, "", name)
      if (name in map) {
        w = length($4); nl = " " map[name]
        while (length(nl) < w) nl = nl " "
        $4 = nl
      }
    }
    { print }
  ' FS='|' OFS='|'
}

echo "Exporting backend production dependencies…"
SKIP_RUNTIME_CHECKS=true uv export --no-dev --no-emit-project \
  --format requirements-txt > "$TMP_REQS"

echo "Collecting backend licenses…"
BACKEND_TABLE="$(uvx --with-requirements "$TMP_REQS" --with pip-licenses \
  pip-licenses --format=markdown --with-urls --order=license \
  | apply_license_overrides)"

echo "Collecting frontend licenses…"
# --excludePrivatePackages drops the project's own package (llmaixwebui, marked
# "private": true) — it is the project, not a bundled third-party dependency.
FRONTEND_LIST="$(npx --yes license-checker-rseidelsohn \
  --production --start . --markdown --excludePrivatePackages)"

{
  echo "# Third-Party Notices"
  echo
  echo "LLMAIx Web (version \`${VERSION}\`) is distributed under the"
  echo "\`AGPL-3.0-or-later\` license. It bundles the third-party open-source"
  echo "components listed below, each governed by its own license. Full license"
  echo "texts are available in each project's repository (linked below) and in the"
  echo "installed package metadata."
  echo
  echo "> This file is generated by \`scripts/generate-third-party-notices.sh\`."
  echo "> Do not edit it by hand — re-run the script to refresh it."
  echo
  echo "Only dependencies shipped in the production build are listed. Development"
  echo "and build-time tooling (test frameworks, bundlers, local OCR/ML fallback"
  echo "dependencies) are excluded because they are not distributed."
  echo
  echo "## Backend (Python — production dependencies)"
  echo
  echo "$BACKEND_TABLE"
  echo
  echo "## Frontend (npm — production dependencies)"
  echo
  echo "$FRONTEND_LIST"
} > "$OUT"

echo "Wrote $OUT"
